### ISSUE TITLE
Allow users to keep a socket open on sandbox between connections (like Lambda)

### ISSUE THREAD

**Issue by mikemaccana** [architect/sandbox#107]
Related to https://github.com/architect/sandbox/issues/33

> In a real AWS Lambda, [`context.callbackWaitsForEmptyEventLoop = false;`](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) can be set - this allows one to run a lambda without [disconnecting from database](https://www.mongodb.com/blog/post/optimizing-aws-lambda-performance-with-mongodb-atlas-and-nodejs). This is used to keep Lambda connections open on MongoDB, RethinkDB, etc.

The fix for #33 means we don't have to close connections each time we're finished with them, which speeds up the sandbox remarkably.

The next step (this bug) is to allow users to keep a socket open when `context.callbackWaitsForEmptyEventLoop = false;`

I'm not really sure how that would look in terms of arc so just opening it up for discussion.

**Comment by ryanblock** [comment]
I was thinking about this over the weekend as I worked on #33, and assumed it'd come up sooner or later!

### Preface
We recognize that lots of folks want to use Lambda with socket-based databases. However, we maintain that Lambda and cloud functions are an entirely new execution context, and that old, serverful ways of doing things, like keeping sockets open, are no longer best practices – at least until cloud function-friendly HTTP database adapters/services come up to solve for this with legacy databases.

We strongly suggest using a DB like DynamoDB, which does not rely on sockets, and is fast enough to respond to a flood of Lambda requests. As such, I don't think myself or @brianleroux will likely be spending time working on this problem.

That said, it doesn't mean we do not recognize that it **is** a problem, and that many folks are fine with the tradeoffs and issues related to using socket-based databases with Lambda.

### With that out of the way
In order to do what's suggested, we'd likely have to completely rebuild everything about how Sandbox emulates Lambda execution. Real Lambdas are microcontainers based on [Firecracker](https://firecracker-microvm.github.io); Sandbox "Lambdas" are single runtime executions (Node, Python, Ruby, etc.) run as a Node subprocess.

Node subprocesses, of course, don't hang around holding sockets open. They run until execution ends (or they're killed), and then they completely close down. In this way, Sandbox is friendly for local development, as it doesn't leave a ton of dangling process running on your machine. Additionally, this makes local dev in Sandbox actually more deterministic than true Lambda executions, as they aren't subject to subtle bugs related to data cached in global scope (something I wrote an [eslint plugin](https://www.npmjs.com/package/eslint-plugin-no-placeholder-globals) to help detect for folks writing serverless apps)).

Anyhow, the degree of rearchitecting required to make sandbox emulate this functionality is vastly out of scope and not currently a priority for the core maintainers.

But we are, as always, very much open to discussion on how this could be done, and totally happy to review PRs that take this work on (so long as they maintain complete backwards compatibility).

Will leave this issue open for discussion for a while in the hopes that someone would take a closer look; barring that, I'll close it out in the next week or two (but we can, of course, always reopen it later).

**Comment by mikemaccana** [comment]
Thanks Ryan and understood. 

> We strongly suggest using a DB like DynamoDB, which does not rely on sockets

I'm curious: what does Dynamo use instead of sockets? 

I wish / hope AWS would make a Dynamo for Lambda with a better billing model and launch time.

**Comment by mikemaccana** [comment]
Sorry I mistyped. I meant to write:

>  I wish / hope AWS would make a *DocumentDB* for Lambda with a better billing model and launch time.

**Comment by brianleroux** [comment]
closing this one; think these things are all a heckuva lot better these days with AWS and plan to do some deeper digging into both DocumentDB and Managed Cassandra 👍
